name: cargo-build
on: [push]

jobs:
  build:
    runs-on:
      - ubuntu-latest
      - macOS-latest
      - windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build 
        run: cargo build
